name: Main
on: [push]
jobs:
  test:
    name: main
    runs-on: ubuntu-latest

    steps:
    # see https://github.com/actions/checkout
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    # see https://medium.com/google-developer-experts/github-actions-for-android-developers-6b54c8a32f55
    - name: Setup JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8

    - name: run gradle
      run: |
        ./gradlew assemble
